---
creation_rules:
  - # IMPORTANT: This rule MUST be above the others
    path_regex: talos/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1nccjzqrr7uerxfkgr058eral3qxend6dqddnmajtq2tn9tv5hv9q70jx2n"
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1nccjzqrr7uerxfkgr058eral3qxend6dqddnmajtq2tn9tv5hv9q70jx2n"
