apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:iWG7z6VCJktL5H86ndgtyvQFJNkPlgLoNitQg3aTeIEIcdhp,iv:1QXkd/nIBdxoQAmw6oajO9HXptsQfCXiAOmfe1fw0Ms=,tag:YtPjBIgbwalwEnhRDyT0+g==,type:str]
    credentials.json: ENC[AES256_GCM,data:7r3oOaPIZizkkWTU97QPsgioRrtqy4U07yNsP2e+vZh4W15QKw4kN3RRIr6k5WvmzjZvmtT8m/GBjrz3GgvQNc7S0kzKpkiYdC63JNEsFBY9J2gwbkR1DWQTCft5Vr/yt+UEUaD8MkbOg3OYhBUoSpMOuYElGzEEDJR9y6X6GHPALXvgxKbIMKzlXvFmYNBvf55gxFZ1ylr2OPU2yFSQRo/GhpD1WUXJmxu+G/Tbxw==,iv:sFlFMCQVvIBQBDhj8Q21Iy8njl1ATQeun3u0sKuwYjA=,tag:uL9FddxSbmzxkaSCPb5Jxg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nccjzqrr7uerxfkgr058eral3qxend6dqddnmajtq2tn9tv5hv9q70jx2n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZVNUL0dKeS9Ud25QSU9F
            YXl1WU5VcnFWTWZWOXg4cVBTc25LYVB3U0N3CmlqT1cyclNpUzM2Und5Z29NL0pE
            alZROGtwcTF5NVlkc1NId2YzVnhhbVUKLS0tIFZlM1hQNmJETXMxakVSa2tIMC9o
            N2hyR1dNYmRTZGt0TVpGMnNqSXMwMmsKiCZERhfJsZNfOCBUT/iSEQ8IXQCTJPt1
            aPSUcNYlOsL4ev4myprokncW4nD3F2LKd+84J/G0w2Rochc2I3oipw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-02T09:14:05Z"
    mac: ENC[AES256_GCM,data:TNNjtMKsvji85osJKk9d6e5hKI1/lLk/DEjjPTP1CTfJtUKRnNaUPUP9JVfcn/UnD4F2lF6r+WKqrsULRTiOJ+Fiy1UH3HvAfU9lniE+nQFXGy3lfxPsklRFIZ9a8MzZXDJTegCsjkHlnqpjIhDCWiVGUhD/42xlaYmzrenO/P4=,iv:E2FxZO3kMmWJOI/YM0gJmHwRYPz5upz1MqnZSopB6HQ=,tag:T0lwUIP788nOztwUfXrblw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
