---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homeassistant
spec:
  interval: 30m
  chart:
    spec:
      chart: homeassistant
      version: 6.0.3
      sourceRef:
        kind: HelmRepository
        name: pajikos
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    replicaCount: 1
