apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ""
    SECRET_ACME_EMAIL: ""
    SECRET_CLOUDFLARE_TUNNEL_ID: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nccjzqrr7uerxfkgr058eral3qxend6dqddnmajtq2tn9tv5hv9q70jx2n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGTmVPcGRWUkRsUW5mdUZw
            K05FZXUxQUZaZ2RMdkkzN0V5cVNaQXRzUWxnCkVPWmN6U1VuQ3VXREluMWd0bHJw
            SjNyalZoa3ovRkM5QlZNN3lxek5SMzQKLS0tIDZLK1JpelU5YmFQeDZpd2JrV1Jt
            M1ZHL3ppWmpiRlVmOFVBTTcwbFp0ajgKgCo528YLTG81m18EfsofYoyIQVrLn8zN
            nf4J2GM1LdkJlneb5AEN5WXix85AenNEC0oJp04vtaQdCKI8JHUFiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-02T06:59:10Z"
    mac: ENC[AES256_GCM,data:FI18JTqH2Y0GXzyFczDTvK0xD7L17yEzochA32QIbp9djtcGoYpRn53r5oQp9kpvo7OS4BJsXu9vo6/erRglubFh8DzGdnl/+mzjewmEIiljAzP8Wf6H0mCfsOOPQ8Ccm6lwsQipZUbDTvxhGKDQOxFjCqOuL2FrViQ3iOKcPBs=,iv:Vumhfs71tCTqovHC/pWSKbVzvtbJFPKnoMp0v+R1u68=,tag:/+gJKaAQlSjge3TDOYI8NQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
