apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:LwfmcG/4EwyoRw==,iv:QQ3a1nD4Gt3o1ZosHgP0if7/ZHyoyZO6wNr6KL/xojU=,tag:HeD9Gbjdq26EJIH26rRrAw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:0b9lQcxON30oGDuKkXNITEDEiu1nc3Wh6A==,iv:W7RSLZglpGW/ciCoUcEQXb7of9bvuxg+F1j/VxVM7sI=,tag:H7dOOn8HG0HfXqCNft/y3Q==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:zcESjZ8U3YDcTYLXpAF8hsdfmci/Eb5qI9XupwMg9HgDDYGq,iv:T52kc5/kBmSjERTKlFIaPp+j653qi9dwkSguX/f+YFc=,tag:8Z9tp+NcqB1/OnoQrPds2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nccjzqrr7uerxfkgr058eral3qxend6dqddnmajtq2tn9tv5hv9q70jx2n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NnQ4cjgwUEtVMWNFa0hO
            emdGNURhci9lUVhTaktLTnZsaDRrcGF5TWdFCmxraGF2ZnhDcXp1T2Z4eFVLVVdN
            SFJObTFqNC9MTWw4WHJVcFQ2VW92SXcKLS0tIGdHK2xOQWt2VG9FbGNFSHhyWTM3
            L1VST3pMSS94NzJYanVYV1lJOC9KdGsKNAvf59EwCFSW1e0wNhZIzrmatEf8/3eD
            DQz7ycwG3Ezpqv8Dg1tjN47RpPh5RYOObASC3JFAD+bXbf0H9m/wpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-02T09:05:18Z"
    mac: ENC[AES256_GCM,data:tYD9zQFezk+3/dqEFjlRHUDo1OtzhSjnVOaD1Sa9gRQPEcsMi3WEY+vQV334qkg9wBtPasFwPQGWgt/47RRXbDG93YJtggPUoweZcdMVqKoqe/h7GnY3ky6O4g9FVzCCRhkyj811a/PWfbTOuynNJZaCYEfX0OSmt6plLRbg+Kc=,iv:pjXiHNa7D+NV2Zigb8b4YT0LUn7bFTtwv8rrkNAst/M=,tag:pb/CjS3I9Zi0ntiWvDvdGg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
