---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  interval: 30m
  chart:
    spec:
      chart: home-assistant
      version: 0.2.82
      sourceRef:
        kind: HelmRepository
        name: pajikos
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    persistence:
      enabled: true
      storageClass: "openebs-hostpath"
    ingress:
      enabled: true
      className: external
      hosts:
        - host: "homeassistant.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: ImplementationSpecific
      annotations:
        external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
    configuration:
      enabled: true
      forceInit: true
      trusted_proxies:
        - 10.69.0.0/24
