---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: synapse
spec:
  interval: 30m
  chart:
    spec:
      chart: matrix-synapse
      version: 3.9.9
      sourceRef:
        kind: HelmRepository
        name: anance-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    serverName: "${SECRET_DOMAIN}"
    publicServerName: "matrix.${SECRET_DOMAIN}"
    wellknown:
      enabled: true
    persistence:
      storageClass: "openebs-hostpath"
    postgresql:
      auth:
        password: "$(SYNAPSE_POSTGRES_PASSWORD)"
      primary:
        persistence:
          storageClass: "openebs-hostpath"
    redis:
      auth:
        password: "$(SYNAPSE_REDIS_PASSWORD)"
      persistence:
        storageClass: "openebs-hostpath"
    ingress:
      className: external
      annotations:
        external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
