---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: synapse
spec:
  interval: 30m
  chart:
    spec:
      chart: matrix-synapse
      version: 3.9.9
      sourceRef:
        kind: HelmRepository
        name: anance-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    serverName: bickio.com
    publicServerName: matrix.bickio.com
    wellknown:
      enabled: true
    postgresql:
      auth:
        existingSecret: synapse-postgres-secret
      primary:
        persistence:
          storageClass: "openebs-hostpath"
    redis:
      auth:
        existingSecret: synapse-redis-secret
      persistence:
        storageClass: "openebs-hostpath"
    ingress:
      hosts:
        - matrix.bickio.com
      className: external
