apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nccjzqrr7uerxfkgr058eral3qxend6dqddnmajtq2tn9tv5hv9q70jx2n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaN1ZIdjRzaURkRnBmT0NV
            dXJucFRFeEFoTHMvYnRHa0UxZkFqNndrMjA0ClZVV3E4ZFBSY2hlaGtYMktFOFdM
            M3BTMXlrbGF3Q3NpWlBVcVBJdFUwL00KLS0tIGM4UWo2YWtFdnVMaldTMFgrZlkw
            bUh0b0UwbG42aC9JRlF6RFJScUxtSjAK2N+jsjyHZt1SjR4yalA69iSlCponDmuu
            yugyMcVC3C2roLUgeBpV2eEZ1jrdVsjC5lecNkFEhyJsjxAHEctukg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-02T08:21:21Z"
    mac: ENC[AES256_GCM,data:a3R3Z4XxXlyq4hNlP+9qxmzenoaVqPt1B7GuPl8YtP3gS/U3IlWjBbjo8+igRwvCGSUMeQUx+SgVLNy4cWnnLJgOLVOcdx137xWvTu2XL3UzUoL5NL+ykIgE/Pm48oGx3bQ5Bp8RQQVQv7mK0aoO9B84AWvc2nnaspzHU+pYOIU=,iv:UQH9c9NaCrfFcR5yTTNi6bsjM8j4JM46v/rRj4LOxlM=,tag:Ik+51UGaQ0dcgglaakdaNA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
