apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:miBJq9gwwfvdtinJGqyBQ/QFRYaGAh4h5+1vGHHaBqQBPNv7kMVPMQ==,iv:hY3z0b6utJLPH7zCjmqss4zuP1PxdMf16WgneYr13z8=,tag:fHkB32XBgEOAIgRnRwFT9g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nccjzqrr7uerxfkgr058eral3qxend6dqddnmajtq2tn9tv5hv9q70jx2n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKeldzY1hic0QxRFJacGlm
            YlN5WG8vSlcwdUN4VGJXYnBZN2JFWmlZS0ZRCjBzVk5sZWRyRXdkemFMQnhFN3lz
            akQxUERUUmxjRTRLQ09GeFBsbjRZK1kKLS0tIDhIWmYwc0RmSTNqM0FndzRCZlN5
            SkpqUXV0cVBzT2FYT08wdjVKM1h5eHcKwslh30oBhqC0UhDTzVoy2NvEdVe6+gqR
            EXHNQHa9qDfjwHd75oK7Ic1KlLS6aw5ylZOiIEI1/m31p+nNTwbcpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-02T09:14:05Z"
    mac: ENC[AES256_GCM,data:byBoOf+bfWC/fixbVfbwZYGgjcCAmJJvrrgyX5qkPL8tZrp7z2bv8kPIN/pTQdnkZPE2GMPI6HuE5SiqjKoIveUaVuXyVKodEIZ1vfPwHSXQbdAllu2xzs8vAL+zMVTn33asbEjR1KXrVifaOyrWG0U8xqvfPwb/plB8TKgm1Bs=,iv:hyRtOwftHmD7a2e+Ap1LcrF8OLaPWzPMlpkTsWhW1fA=,tag:K1q99UVL4efWwIzXcniQHg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
