---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mosquitto
spec:
  interval: 30m
  chart:
    spec:
      chart: mosquitto
      version: 16.2.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    service:
      main:
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: "192.168.1.96"
        ports:
          main:
            port: 1883
            targetPort: 1883
    persistence:
      data:
        storageClass: "openebs-hostpath"
      configinc:
        storageClass: "openebs-hostpath"
